
version: 2

sources:
    - name: raw
      schema: gz_raw_data
      tables:
          - name: sales
            identifier: raw_gz_sales
            description: Revenue par produit dans chaque commande
            loaded_at_field: "CAST(date_date AS TIMESTAMP)"
            freshness: 
              warn_after:
                count: 90
                period: day
            
            columns:
              - name: date_date
                description: date de vente
              - name: orders_id
                description: numéro de commande
              - name: pdt_id
                description: numéro de produit
              - name: revenue
                description: prix de vente
              - name: quantity
                description: quantité
              - name: "(orders_id || '-' || pdt_id)"
                description: primary key of the table
                tests:
                - unique
                - not_null

          - name: product
            identifier: raw_gz_product
            description: Liste des produits avec leur prix d'achat
            columns:
              - name: products_id
                description: numéro de produit
                tests:
                  - not_null
                  - unique
              - name: purchSE_PRICE
                description: prix d'achat

          - name: ship
            identifier: raw_gz_ship
            description: Frais de livraisons par commande
            columns:
              - name: orders_id
                description: numéro de commande
                tests:
                  - not_null
                  - unique
              - name: shipping_fee
                description: coût de livraison
              - name: shipping_fee1
                description: coût de livraison
              - name: logCost
                description: coût de logistique
              - name: ship_cost
                description: coût de transporteur

          - name: adwords
            identifier: raw_gz_adwords
            description: coût des publicités google par campagnes
            columns:
              - name: date_date
                description: date de la campagne
              - name: paid_source
                description: plateforme 
              - name: campaign_key
                description: clé de la campagne
              - name: camPGN_name
                description: nom de la campagne
              - name: ads_cost
                description: coût de la publicité
              - name: impression
                description: nombre d'impression de la campagne
              - name: click
                description: nombre de clics de la campagne
              - name: "(date_date || '-' || campaign_key)"
                description: primary key of the table
                tests:
                - unique
                - not_null

          - name: bing
            identifier: raw_gz_bing
            description: coût des publicités bing par campagnes
            columns:
              - name: date_date
                description: date de la campagne
              - name: paid_source
                description: plateforme 
              - name: campaign_key
                description: clé de la campagne
              - name: camPGN_name
                description: nom de la campagne
              - name: ads_cost
                description: coût de la publicité
              - name: impression
                description: nombre d'impression de la campagne
              - name: click
                description: nombre de clics de la campagne
              - name: "(date_date || '-' || campaign_key)"
                description: primary key of the table
                tests:
                - unique
                - not_null

          - name: criteo
            identifier: raw_gz_criteo
            description: coût des publicités criteo par campagnes
            columns:
              - name: date_date
                description: date de la campagne
              - name: paid_source
                description: plateforme 
              - name: campaign_key
                description: clé de la campagne
              - name: camPGN_name
                description: nom de la campagne
              - name: ads_cost
                description: coût de la publicité
              - name: impression
                description: nombre d'impression de la campagne
              - name: click
                description: nombre de clics de la campagne
              - name: "(date_date || '-' || campaign_key)"
                description: primary key of the table
                tests:
                - unique
                - not_null

          - name: facebook
            identifier: raw_gz_facebook
            description: coût des publicités facebook par campagnes
            columns:
              - name: date_date
                description: date de la campagne
              - name: paid_source
                description: plateforme 
              - name: campaign_key
                description: clé de la campagne
              - name: camPGN_name
                description: nom de la campagne
              - name: ads_cost
                description: coût de la publicité
              - name: impression
                description: nombre d'impression de la campagne
              - name: click
                description: nombre de clics de la campagne
              - name: "(date_date || '-' || campaign_key)"
                description: primary key of the table
                tests:
                - unique
                - not_null

          
models:
   - name: int_campaigns
     description: coût des publicités par campagnes
     columns:
         - name: date_date
           description: date de la campagne
         - name: paid_source
           description: plateforme 
         - name: campaign_key
           description: clé de la campagne
         - name: campaign_name
           description: nom de la campagne
         - name: ads_cost
           description: coût de la publicité
         - name: impression
           description: nombre d'impression de la campagne
         - name: click
           description: nombre de clics de la campagne
         - name: "(date_date || '-' || campaign_key)"
           description: primary key of the table
           tests:
              - unique
              - not_null
   - name: int_campaigns_days
     description: coût des publicités par jours
     columns:
         - name: date_date
           description: date de la campagne
           tests:
              - unique
              - not_null             
         - name: ads_cost
           description: coût de la publicité
         - name: ads_impression
           description: nombre d'impression de la campagne
         - name: ads_click
           description: nombre de clics de la campagne